services:
  mysql:
    build:
      context: ./
      dockerfile: db/mysql/dev/Dockerfile
    container_name: dunktomic_db
    restart: "no"
    environment:
      MYSQL_ROOT_PASSWORD: root_password
    expose:
      - 3306
    ports:
      - "3306:3306"
    healthcheck:
      test: mysql --user=root --password=$$MYSQL_ROOT_PASSWORD --silent --execute "use dunktomic_db"
      interval: 10s
      timeout: 10s
      retries: 5

  keycloak:
    build:
      context: ./
      dockerfile: keycloak/Dockerfile
    container_name: dunktomic_keycloak
    environment:
      KEYCLOAK_ADMIN: admin
      KEYCLOAK_ADMIN_PASSWORD: change_me
      KC_HEALTH_ENABLED: true
    depends_on:
      mysql:
        condition: service_healthy
    expose:
      - 8080
    ports:
      - "8080:8080"
    healthcheck:
      test: [ "CMD-SHELL", "exec 3<>/dev/tcp/127.0.0.1/8080;echo -e \"GET /health/ready HTTP/1.1\r\nhost: http://localhost\r\nConnection: close\r\n\r\n\" >&3;grep \"HTTP/1.1 200 OK\" <&3" ]
      start_period: 30s
      interval: 15s
      timeout: 5s
      retries: 5

  backend:
    build:
      context: ./
      dockerfile: backend/deployment/Dockerfile
    container_name: dunktomic_backend
    expose:
      - 8081
    ports:
      - "8081:8081"
    depends_on:
      mysql:
        condition: service_healthy
      keycloak:
        condition: service_healthy
