services:
  mysql:
    build:
      context: ./
      dockerfile: db/mysql/dev/Dockerfile
    container_name: dunktomic_db
    restart: "no"
    environment:
      MYSQL_ROOT_PASSWORD: root_password
    expose:
      - 3306
    ports:
      - "3305:3306"
    healthcheck:
      test: mysql --user=root --password=$$MYSQL_ROOT_PASSWORD --silent --execute "use dunktomic_db"
      interval: 15s
      timeout: 10s
      retries: 10
