services:
  mysql:
    build:
      context: ./
      dockerfile: db/mysql/dev/Dockerfile
    container_name: dunktomic_db
    restart: "no"
    environment:
      MYSQL_ROOT_PASSWORD: root_password
    expose:
      - 3306
    ports:
      - "3306:3306"
    healthcheck:
      test: mysql --user=root --password=$$MYSQL_ROOT_PASSWORD --silent --execute "use dunktomic_db"
      interval: 15s
      timeout: 10s
      retries: 10

  keycloak:
    build:
      context: ./
      dockerfile: keycloak/Dockerfile
    container_name: dunktomic_keycloak
    environment:
      - KEYCLOAK_ADMIN=admin
      - KEYCLOAK_ADMIN_PASSWORD=change_me
    ports:
      - "8080:8080"
